movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movies_id>', views.detail, name='detail')

]

vidly/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResource
from . import views

movie_resource = MovieResource()

urlpatterns = [
    path('',views.home),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('api/', include(movie_resource.urls))
]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie

class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = 'movies'
        excludes = ['date_created','id','number_in_stock']

movies/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Genre(models.Model):
    
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Movie(models.Model):

    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)
    

api/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
from django.http import HttpResponse,Http404
from django.shortcuts import render, get_object_or_404
from .models import Movie


def index(request):
    movies = Movie.objects.all()
    return render(request, 'movies/index.html', {'movies': movies})


def detail(request,movies_id):
        movie = get_object_or_404(Movie, id=movies_id)
        return render(request, 'movies/detail.html', {'movie':movie})

vidly/views.py
from django.shortcuts import render

def home(request):
    return render(request,'home.html')

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content  %}
    <table class="table table-dark table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Genre</th>
                <th>Imdb Rate</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{movie.title}}</td>
                <td>{{movie.genre}}</td>
                <td>{{movie.daily_rate}}</td>
            </tr>
        </tbody>
    </table>
{% endblock  %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Genre</th>
                <th>Stock</th>
                <th>Imdb Rate</th>
            </tr>
        </thead>
        <tbody>
            {% for movie in movies %}
            <tr>
                <td>
                    <a href = "{% url 'movies:detail' movie.id %}">{{movie.title}}</a>
                </td>
                <td>{{movie.genre}}</td>
                <td>{{movie.number_in_stock}}</td>
                <td>{{movie.daily_rate}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock  %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vidly</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Vidly</a>
        </div>
    </nav>
    <main class="container">
    {% block content %}
    {% endblock  %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'movies:index' %}">Movies</a>
{% endblock  %}